import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Header from "@/components/Header/Header";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="fr">
            <body>
                {/* Header */}
                <Header />

                {/* Nav */}
                <nav className="p-5 bg-red-300 mb-10">
                    <ul className="flex gap-5 justify-center my-5">
                        <li className="nav-item">
                            <Link href="/">Accueil</Link>
                        </li>
                        <li className="nav-item">
                            <Link href="/blog">Blog</Link>
                        </li>
                        <li className="nav-item">
                            <Link href="/about">A propos</Link>
                        </li>
                        <li className="nav-item">
                            <Link href="/create">Creer un post</Link>
                        </li>
                    </ul>
                </nav>

                {/* Content */}
                {children}

                {/* Notification */}
                <ToastContainer position="bottom-right" theme="dark" />
            </body>
        </html>
    );
}
